name: Deploy to Self-Hosted Runner

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Trivy fs scan
        run: trivy fs --format table -o fs.html .

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         
        

      - name: Build Docker containers
        run: |
          # Navigate to the application directory
          #cd /home/sambhav/sambhav

          # Build the Docker containers from the Dockerfile(s)
          #docker-compose build

          # Optional: Start the containers
         # docker-compose down
        #  docker-compose up -d

